/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-27 04:37:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.actiontag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import servlet.vo.Member;

public final class response_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
      servlet.vo.Member member = null;
      member = (servlet.vo.Member) _jspx_page_context.getAttribute("member", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (member == null){
        member = new servlet.vo.Member();
        _jspx_page_context.setAttribute("member", member, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      servlet.vo.Member sessionMember = null;
      synchronized (session) {
        sessionMember = (servlet.vo.Member) _jspx_page_context.getAttribute("sessionMember", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sessionMember == null){
          sessionMember = new servlet.vo.Member();
          _jspx_page_context.setAttribute("sessionMember", sessionMember, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8>\r\n");
      out.write("<title>Response</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\tExpression Tag 이용<br/>\r\n");
      out.write("\tID : ");
      out.print(member.getId() );
      out.write(" <br/>\r\n");
      out.write("\tPassword : ");
      out.print(member.getPassword() );
      out.write("  <br/>\r\n");
      out.write("\t이름 : ");
      out.print(member.getName() );
      out.write("  <br/>\r\n");
      out.write("\t나이 : ");
      out.print(member.getAge() );
      out.write("  <br/>\r\n");
      out.write("\t결혼 여부 : ");
      out.print(member.isMarriage()==true?"기혼":"미혼");
      out.write("  <p/>\r\n");
      out.write("\r\n");
      out.write("\tsetProperty 이후 getProperty 이용<br/>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("member"), "id", "id-00", null, null, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("member"), "password", "1234", null, null, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("member"), "name", "김철수", null, null, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("member"), "age", "22", null, null, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("member"), "marriage", "false", null, null, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tID : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((servlet.vo.Member)_jspx_page_context.findAttribute("member")).getId())));
      out.write("<br/>\r\n");
      out.write("\tpassword : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((servlet.vo.Member)_jspx_page_context.findAttribute("member")).getPassword())));
      out.write("<br/>\r\n");
      out.write("\t이름 :");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((servlet.vo.Member)_jspx_page_context.findAttribute("member")).getName())));
      out.write("<br/>\r\n");
      out.write("\t나이 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((servlet.vo.Member)_jspx_page_context.findAttribute("member")).getAge())));
      out.write("<br/>\r\n");
      out.write("\t결혼여부 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((servlet.vo.Member)_jspx_page_context.findAttribute("member")).isMarriage())));
      out.write("<p/>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Session scope의 session-member attribute의 속성 값들 출력 -->\r\n");
      out.write("\t<h2>회원정보 - session</h2>\r\n");
      out.write("\tID : ");
      out.print(sessionMember.getId() );
      out.write(" <br/>\r\n");
      out.write("\tPassword : ");
      out.print(sessionMember.getPassword() );
      out.write("  <br/>\r\n");
      out.write("\t이름 : ");
      out.print(sessionMember.getName() );
      out.write("  <br/>\r\n");
      out.write("\t나이 : ");
      out.print(sessionMember.getAge() );
      out.write("  <br/>\r\n");
      out.write("\t결혼 여부 : ");
      out.print(sessionMember.isMarriage()==true?"기혼":"미혼");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
