/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-27 06:42:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.actiontag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import servlet.vo.Member;

public final class response2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      servlet.vo.Member member = null;
      member = (servlet.vo.Member) _jspx_page_context.getAttribute("member", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (member == null){
        member = new servlet.vo.Member();
        _jspx_page_context.setAttribute("member", member, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t<!-- jsp:setProperty name='member' property='name' value='이철수'/ -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("member"), request);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>회원정보-response2.jsp</h2>\r\n");
      out.write("\tID : ");
      out.print(member.getId() );
      out.write(" <br/>\r\n");
      out.write("\t이름 : ");
      out.print(member.getName() );
      out.write("  <br/>\r\n");
      out.write("\t나이 : ");
      out.print(member.getAge() );
      out.write("  <br/>\r\n");
      out.write("\t결혼 여부 : ");
      out.print(member.isMarriage()==true?"기혼":"미혼");
      out.write("<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 요청파라미터로 받은 값을 session scope의 member2 Attribute객체의 property에 넣으세요. -->\r\n");
      out.write("\t<h2>Session의 회원 정보</h2>\r\n");
      out.write("\t");
      servlet.vo.Member member2 = null;
      synchronized (session) {
        member2 = (servlet.vo.Member) _jspx_page_context.getAttribute("member2", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (member2 == null){
          member2 = new servlet.vo.Member();
          _jspx_page_context.setAttribute("member2", member2, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("member2"), request);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tID : ");
      out.print(member2.getId() );
      out.write(" <br/>\r\n");
      out.write("\tPassword : ");
      out.print(member2.getPassword() );
      out.write("  <br/>\r\n");
      out.write("\t이름 : ");
      out.print(member2.getName() );
      out.write("  <br/>\r\n");
      out.write("\t나이 : ");
      out.print(member2.getAge() );
      out.write("  <br/>\r\n");
      out.write("\t결혼 여부 : ");
      out.print(member2.isMarriage()==true?"기혼":"미혼");
      out.write("<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href='/myjsp/actiontag/request.jsp'>요청페이지</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
